name: build

on: [push]

env:
  DOTNET_VERSION: 8.0.x
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./ThAmCo.Staff
  PUBLISH_PATH: ./myapp
  TESTRESULTS_PATH: ./test-results
  AZURE_WEBAPP_NAME: JSFStaff
  Auth0__ClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build code
        run: |
          dotnet build \
            --configuration $BUILD_CONFIGURATION \
            --no-restore
            
      - name: Run unit tests
        run: |
          dotnet test \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --logger trx \
            --results-directory $TESTRESULTS_PATH
        env:
          Auth0__ClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}
            
      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ env.TESTRESULTS_PATH }}
        if: ${{ always() }}
        
      - name: Package build
        run: |
          dotnet publish $PROJECT_PATH \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --output $PUBLISH_PATH
            
      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}
          
  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    environment: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: ${{ env.PUBLISH_PATH }}
